name: Build Complete Cherry Studio

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    timeout-minutes: 90

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install and configure Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.6.0 --activate
          yarn --version

      - name: Install TypeScript globally
        run: |
          npm install -g typescript

      - name: Install NSIS
        run: |
          choco install nsis -y
          refreshenv

      - name: Clear yarn cache (if needed)
        run: |
          yarn cache clean --all
        continue-on-error: true

      - name: Install Dependencies (fresh install)
        run: |
          yarn install --no-immutable
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Download platform-specific packages
        run: |
          node scripts/build-npm.js windows
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Clean previous builds
        run: |
          Remove-Item -Path "dist*" -Recurse -Force -ErrorAction SilentlyContinue
          Write-Host "Cleaned previous build artifacts"
        shell: pwsh

      - name: Build Application (skip typecheck)
        run: |
          yarn build:win:x64:quick
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          CI: true

      - name: Generate timestamp
        id: timestamp
        run: |
          $timestamp = Get-Date -Format "yyyyMMdd-HHmm"
          echo "timestamp=$timestamp" >> $env:GITHUB_OUTPUT
        shell: pwsh

      - name: List build output
        shell: pwsh
        run: |
          Write-Host "Build output directory contents:"
          if (Test-Path "dist") {
            Get-ChildItem -Path "dist" -Recurse | ForEach-Object {
              Write-Host "  $($_.FullName)"
            }
          } else {
            Write-Host "dist directory not found!"
          }

      - name: Organize build artifacts
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "release"
          $timestamp = "${{ steps.timestamp.outputs.timestamp }}"
          
          # Find and copy setup installer
          $setupFiles = Get-ChildItem -Path "dist" -Name "*setup*.exe" -ErrorAction SilentlyContinue
          if ($setupFiles) {
            foreach ($setupFile in $setupFiles) {
              $newName = "Cherry-Studio-COMPLETE-$timestamp-setup.exe"
              Copy-Item "dist\$setupFile" "release\$newName"
              Write-Host "Setup installer: $setupFile -> $newName"
            }
          } else {
            Write-Host "No setup installer found"
          }
          
          # Find and copy portable executable
          $portableFiles = Get-ChildItem -Path "dist" -Name "*portable*.exe" -ErrorAction SilentlyContinue
          if ($portableFiles) {
            foreach ($portableFile in $portableFiles) {
              $newName = "Cherry-Studio-COMPLETE-$timestamp-portable.exe"
              Copy-Item "dist\$portableFile" "release\$newName"
              Write-Host "Portable executable: $portableFile -> $newName"
            }
          } else {
            Write-Host "No portable executable found"
          }
          
          # Copy any other important files
          $otherFiles = Get-ChildItem -Path "dist" -Name "*.yml" -ErrorAction SilentlyContinue
          if ($otherFiles) {
            foreach ($file in $otherFiles) {
              Copy-Item "dist\$file" "release\$file"
              Write-Host "Copied: $file"
            }
          }
          
          # Generate release info
          @"
          # Cherry Studio - Complete Build (Size Optimized)
          
          **Build Date:** $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss UTC')
          **Build ID:** $timestamp
          **Platform:** Windows x64
          **Commit:** ${{ github.sha }}
          
          ## Optimizations Applied
          - Fixed recursive build artifact inclusion
          - Enabled ASAR compression with selective unpacking
          - Extensive file exclusion rules for smaller package size
          - Resolved opendal module loading issues
          - Fixed NSIS installer tool availability
          
          ## Files
          "@ | Out-File -FilePath "release\README.md" -Encoding UTF8
          
          # Generate checksums
          Get-ChildItem -Path "release" -File | Where-Object { $_.Name -ne 'README.md' } | ForEach-Object {
            $hash = (Get-FileHash -Algorithm SHA256 $_.FullName).Hash.ToLower()
            "- **$($_.Name)** - SHA256: $hash" | Out-File -FilePath "release\README.md" -Append -Encoding UTF8
          }
          
          Write-Host "Release files prepared:"
          Get-ChildItem -Path "release" | ForEach-Object { Write-Host "  $($_.Name)" }

      - name: Upload Complete Build
        uses: actions/upload-artifact@v4
        with:
          name: Cherry-Studio-COMPLETE-${{ steps.timestamp.outputs.timestamp }}
          path: release/*
          retention-days: 30
          compression-level: 6

      - name: Build Summary
        shell: pwsh
        run: |
          Write-Host ""
          Write-Host "=== CHERRY STUDIO BUILD COMPLETED ==="
          Write-Host ""
          Write-Host "✅ Complete Cherry Studio with size optimization has been built successfully!"
          Write-Host ""
          Write-Host "📦 Download your application from the Artifacts section above."
          Write-Host ""
          Write-Host "🔧 Fixes Applied:"
          Write-Host "   - Fixed recursive build artifact inclusion (was causing 4.2GB+ size)"
          Write-Host "   - Enabled ASAR compression with selective unpacking"
          Write-Host "   - Added extensive file exclusion rules"
          Write-Host "   - Resolved opendal module loading issues"
          Write-Host "   - Fixed NSIS installer tool availability"
          Write-Host "   - Package size should now be in reasonable range (few hundred MB)"
          Write-Host ""
          Write-Host "🚀 Ready to use - Cherry Studio should now work without module errors!"
          Write-Host ""